Repository Wootecho-side/chrome-woowaplanet, pull requests merged in 2025-06, with the labels that each got.

#12 Refactor/animation 행성이 인터랙션 수정
  src/components/Planet/Planet.styles.ts
  src/components/Planet/Planet.tsx
  src/components/PlanetEyes/PlanetEyes.tsx
  src/hooks/useShakeAnimation.ts
  src/stories/components/Planet.stories.tsx
Labels: enhancement

#14 Feature/ring 고리 SVG 변경 및 버튼 다크모드 대응 추가 #13
  public/button/dice-darkMode.svg
  public/button/github-darkMode.svg
  public/button/inventory-darkMode.svg
  src/components/BackgroundWrapper/BackgroundWrapper.tsx
  src/components/DownRing/DownRing.tsx
  src/components/IconButton/IconButton.tsx
  src/components/Planet/Planet.styles.ts
  src/components/PlanetBody/PlanetBody.tsx
  src/components/UpRing/UpRing.tsx
  src/hooks/useDarkMode.ts
  src/stories/App.stories.tsx
Labels: enhancement

#16 Feature/inventory 인벤토리 기능 추가 및 App 레이아웃 구성
  public/satellite/cat.png
  public/satellite/hmm.png
  public/satellite/mouse.png
  public/satellite/star.png
  src/App.tsx
  src/components/BackgroundWrapper/BackgroundWrapper.styles.ts
  src/components/BackgroundWrapper/BackgroundWrapper.tsx
  src/components/IconButton/ButtonTypes.ts
  src/components/IconButton/DiceButton/DiceButton.tsx
  src/components/IconButton/GithubButton/GithubButton.tsx
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/InventoryButton/InventoryButton.tsx
  src/components/Inventory/Inventory.styles.ts
  src/components/Inventory/Inventory.tsx
  src/components/Inventory/InventoryTypes.ts
  src/components/OrbitalMoving/OrbitalMoving.tsx
  src/components/Planet/Planet.styles.ts
  src/data/SatelliteData.ts
  src/stories/components/Inventory.stories.tsx
Labels: enhancement

#21 Feature/draw 위성이 뽑기 로직 구현
  src/App.tsx
  src/components/IconButton/DiceButton/DiceButton.tsx
  src/components/Inventory/Inventory.tsx
  src/components/Inventory/InventoryTypes.ts
  src/components/Shop/Shop.styles.tsx
  src/components/Shop/Shop.tsx
  src/constants/config.ts
  src/contexts/StorageContext/StorageProvider.tsx
  src/contexts/StorageContext/useStorageContext.ts
  src/hooks/useSatelliteDraw.ts
  src/main.tsx
  src/pages/MainPage.tsx
  src/utils/getNewSatellite.ts
  src/utils/getRandom.ts
Labels: enhancement

#25 Feature/color theme 행성이 색상 변경 기능 추가
  src/components/DownRing/DownRing.tsx
  src/components/Planet/Planet.tsx
  src/components/PlanetBody/PlanetBody.tsx
  src/components/PlanetEyes/PlanetEyes.tsx
  src/components/Ring.styles.ts
  src/components/UpRing/UpRing.tsx
  src/pages/MainPage.tsx
  src/styles/planetColorThemes.ts
Labels: enhancement

#28 Feature/svg svg 작업 및 새로고침 시 깜빡임 현상 수정
  public/satellite/balloon.png
  public/satellite/clover.png
  public/satellite/ghost.png
  public/satellite/watermelon.png
  src/components/BackgroundWrapper/BackgroundWrapper.tsx
  src/components/Planet/Planet.styles.ts
  src/components/Planet/Planet.tsx
  src/constants/config.ts
  src/data/SatelliteData.ts
  src/pages/MainPage.tsx
Labels: bug

#34 Feature/backlight 네온 효과 구현 및 추가
  src/components/Backlight/Backlight.styles.ts
  src/components/Backlight/Backlight.tsx
  src/components/OrbitalMoving/OrbitalMoving.styles.ts
  src/components/Planet/Planet.tsx
  src/components/Satellite/Satellite.styles.ts
  src/components/Satellite/Satellite.tsx
  src/stories/components/Backlight.stories.tsx
Labels: enhancement

#38 Feature/eye 즉각적으로 반응하는 눈동자 움직임 구현
  src/components/EyeMoving/EyeMoving.styles.ts
  src/components/EyeMoving/EyeMoving.tsx
  src/components/Planet/Planet.styles.ts
  src/components/Planet/Planet.tsx
  src/components/PlanetBody/PlanetBody.tsx
  src/components/PlanetEyes/PlanetEyes.tsx
  src/hooks/useEyeMoving.ts
  src/stories/components/EyeMoving.stories.tsx
Labels: bug, enhancement

#49 Feature/bookmark open
  src/components/Bookmark/Bookmark.tsx
  src/constants/storage.ts
  src/contexts/StorageContext/StorageProvider.tsx
  src/contexts/StorageContext/useStorageContext.ts
  src/hooks/useInitStorage.ts
Labels: enhancement

#50 Feature/pagination 위성이 인벤토리 페이지네이션 추가
  public/button/left-darkMode.svg
  public/button/left.svg
  public/button/right-darkMode.svg
  public/button/right.svg
  src/components/IconButton/ButtonTypes.ts
  src/components/Inventory/Inventory.styles.ts
  src/components/Inventory/Inventory.tsx
  src/components/Inventory/InventoryTypes.ts
  src/components/Satellite/Satellite.styles.ts
  src/hooks/useSatellitePagination.ts
Labels: enhancement

#51 Feature/animation 행성이 / 위성이 애니메이션 추가
  src/components/OrbitalMoving/OrbitalMoving.tsx
  src/components/Planet/Planet.tsx
  src/hooks/useShakeAnimation.ts
  src/pages/MainPage.tsx
Labels: enhancement

#54 Chore/manifest 배포용 설정 PR
  docs/privacy-policy.md
  index.html
  public/icons/icon128.png
  public/icons/icon16.png
  public/icons/icon48.png
  public/manifest.json
  public/planet.svg
  src/stories/components/Planet.stories.tsx
  vite.config.ts
Labels: documentation, enhancement
